travis:
  secure:
    BINSTAR_TOKEN: YjYv0rhUhtcSFXuLe0/NvUzfTjVoWTjU3M6ygYhiAwKqCxD21n4E+V82CUC9vAbKBT0Qh3/3AdadiQ9TuTBwB2xhmwDQblyuDr+i2c8Yt+ePwrGMtWu+Ak/mNq9mrDm0lPkEkDfLQoVIBB1mc9bn0yTiyyGKsh4K0xTgbRFUDBDQHb4sA8uued9JFCNBMullsBngdQx749AghgSh6gs8ZAVdz3E9UeHSohlandbFU8uHIZnksbYYgDfktWsHDhy+e9/sDL2ktMSXCvZCY77aLfeOLEp4CaDZaIQ7GJaM73HvxPFkpZEK6hj6Mjex8L683A2FNlGsfzsyBHo8x1QS1wZzhdXIDGqyTaUmJNV28OGpty28R/0N/cbhc7Vf8cIak/u9p1QleJ9zwAk7SDn4Q9p9e7JNcLBvIX5HyzVrcQ5/PQ2CqLDHNtbJbaUojzzaN0Tsd/yBwYD/wXXPD2cuP6wDMnL8z+7OTBk6qleyM8zPEyp7p3KC1kCqG8ryAFnDFyt4paOgDpRwa0sz5VxGgs13Hj2lLx5aU1jPPtWZUmBZCGf7vZh9DMjBcJpCUzaiJxvEaqALne+3spiGHu4MycWIAzdsDS67Z53jQBFxefscviD60K+beDsnypID1IHVluFa1eVAdUEl6/sfZLv0GfKCAke+tyKUpB7DPtLPPYY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
